[package]
name = "nostr-sdk-wasm-example"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]

[dependencies]
nostr-sdk = { git = "https://github.com/rust-nostr/nostr", rev = "6e2180b51d8f6ef992531641689156b6e178cbed", features = ["rest-api"] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
yew = { version = "0.20", features = ["csr"] }
